<?php

namespace RWC\TwitterStream;

/**
 * @method RuleBuilder isRetweet()
 * @method RuleBuilder isNotRetweet()
 * @method RuleBuilder orIsRetweet()
 * @method RuleBuilder orIsNotRetweet()
 * @method RuleBuilder andIsRetweet()
 * @method RuleBuilder andIsNotRetweet()
 * @method RuleBuilder isReply()
 * @method RuleBuilder isNotReply()
 * @method RuleBuilder orIsReply()
 * @method RuleBuilder orIsNotReply()
 * @method RuleBuilder andIsReply()
 * @method RuleBuilder andIsNotReply()
 * @method RuleBuilder isQuote()
 * @method RuleBuilder isNotQuote()
 * @method RuleBuilder orIsQuote()
 * @method RuleBuilder orIsNotQuote()
 * @method RuleBuilder andIsQuote()
 * @method RuleBuilder andIsNotQuote()
 * @method RuleBuilder isVerified()
 * @method RuleBuilder isNotVerified()
 * @method RuleBuilder orIsVerified()
 * @method RuleBuilder orIsNotVerified()
 * @method RuleBuilder andIsVerified()
 * @method RuleBuilder andIsNotVerified()
 * @method RuleBuilder hasHashtags()
 * @method RuleBuilder hasNotHashtags()
 * @method RuleBuilder orHasHashtags()
 * @method RuleBuilder orHasNotHashtags()
 * @method RuleBuilder andHasHashtags()
 * @method RuleBuilder andHasNotHashtags()
 * @method RuleBuilder hasCashtags()
 * @method RuleBuilder hasNotCashtags()
 * @method RuleBuilder orHasCashtags()
 * @method RuleBuilder orHasNotCashtags()
 * @method RuleBuilder andHasCashtags()
 * @method RuleBuilder andHasNotCashtags()
 * @method RuleBuilder hasLinks()
 * @method RuleBuilder hasNotLinks()
 * @method RuleBuilder orHasLinks()
 * @method RuleBuilder orHasNotLinks()
 * @method RuleBuilder andHasLinks()
 * @method RuleBuilder andHasNotLinks()
 * @method RuleBuilder hasMentions()
 * @method RuleBuilder hasNotMentions()
 * @method RuleBuilder orHasMentions()
 * @method RuleBuilder orHasNotMentions()
 * @method RuleBuilder andHasMentions()
 * @method RuleBuilder andHasNotMentions()
 * @method RuleBuilder hasMedia()
 * @method RuleBuilder hasNotMedia()
 * @method RuleBuilder orHasMedia()
 * @method RuleBuilder orHasNotMedia()
 * @method RuleBuilder andHasMedia()
 * @method RuleBuilder andHasNotMedia()
 * @method RuleBuilder hasVideos()
 * @method RuleBuilder hasNotVideos()
 * @method RuleBuilder orHasVideos()
 * @method RuleBuilder orHasNotVideos()
 * @method RuleBuilder andHasVideos()
 * @method RuleBuilder andHasNotVideos()
 * @method RuleBuilder hasGeo()
 * @method RuleBuilder hasNotGeo()
 * @method RuleBuilder orHasGeo()
 * @method RuleBuilder orHasNotGeo()
 * @method RuleBuilder andHasGeo()
 * @method RuleBuilder andHasNotGeo()
 * @method RuleBuilder from(string|array $value)
 * @method RuleBuilder notFrom(string|array $value)
 * @method RuleBuilder orFrom(string|array $value)
 * @method RuleBuilder orNotFrom(string|array $value)
 * @method RuleBuilder andFrom(string|array $value)
 * @method RuleBuilder andNotFrom(string|array $value)
 * @method RuleBuilder to(string|array $value)
 * @method RuleBuilder notTo(string|array $value)
 * @method RuleBuilder orTo(string|array $value)
 * @method RuleBuilder orNotTo(string|array $value)
 * @method RuleBuilder andTo(string|array $value)
 * @method RuleBuilder andNotTo(string|array $value)
 * @method RuleBuilder url(string|array $value)
 * @method RuleBuilder notUrl(string|array $value)
 * @method RuleBuilder orUrl(string|array $value)
 * @method RuleBuilder orNotUrl(string|array $value)
 * @method RuleBuilder andUrl(string|array $value)
 * @method RuleBuilder andNotUrl(string|array $value)
 * @method RuleBuilder retweetsOf(string|array $value)
 * @method RuleBuilder notRetweetsOf(string|array $value)
 * @method RuleBuilder orRetweetsOf(string|array $value)
 * @method RuleBuilder orNotRetweetsOf(string|array $value)
 * @method RuleBuilder andRetweetsOf(string|array $value)
 * @method RuleBuilder andNotRetweetsOf(string|array $value)
 * @method RuleBuilder context(string|array $value)
 * @method RuleBuilder notContext(string|array $value)
 * @method RuleBuilder orContext(string|array $value)
 * @method RuleBuilder orNotContext(string|array $value)
 * @method RuleBuilder andContext(string|array $value)
 * @method RuleBuilder andNotContext(string|array $value)
 * @method RuleBuilder entity(string|array $value)
 * @method RuleBuilder notEntity(string|array $value)
 * @method RuleBuilder orEntity(string|array $value)
 * @method RuleBuilder orNotEntity(string|array $value)
 * @method RuleBuilder andEntity(string|array $value)
 * @method RuleBuilder andNotEntity(string|array $value)
 * @method RuleBuilder conversationId(string|array $value)
 * @method RuleBuilder notConversationId(string|array $value)
 * @method RuleBuilder orConversationId(string|array $value)
 * @method RuleBuilder orNotConversationId(string|array $value)
 * @method RuleBuilder andConversationId(string|array $value)
 * @method RuleBuilder andNotConversationId(string|array $value)
 * @method RuleBuilder bio(string|array $value)
 * @method RuleBuilder notBio(string|array $value)
 * @method RuleBuilder orBio(string|array $value)
 * @method RuleBuilder orNotBio(string|array $value)
 * @method RuleBuilder andBio(string|array $value)
 * @method RuleBuilder andNotBio(string|array $value)
 * @method RuleBuilder bioName(string|array $value)
 * @method RuleBuilder notBioName(string|array $value)
 * @method RuleBuilder orBioName(string|array $value)
 * @method RuleBuilder orNotBioName(string|array $value)
 * @method RuleBuilder andBioName(string|array $value)
 * @method RuleBuilder andNotBioName(string|array $value)
 * @method RuleBuilder bioLocation(string|array $value)
 * @method RuleBuilder notBioLocation(string|array $value)
 * @method RuleBuilder orBioLocation(string|array $value)
 * @method RuleBuilder orNotBioLocation(string|array $value)
 * @method RuleBuilder andBioLocation(string|array $value)
 * @method RuleBuilder andNotBioLocation(string|array $value)
 * @method RuleBuilder place(string|array $value)
 * @method RuleBuilder notPlace(string|array $value)
 * @method RuleBuilder orPlace(string|array $value)
 * @method RuleBuilder orNotPlace(string|array $value)
 * @method RuleBuilder andPlace(string|array $value)
 * @method RuleBuilder andNotPlace(string|array $value)
 * @method RuleBuilder placeCountry(string|array $value)
 * @method RuleBuilder notPlaceCountry(string|array $value)
 * @method RuleBuilder orPlaceCountry(string|array $value)
 * @method RuleBuilder orNotPlaceCountry(string|array $value)
 * @method RuleBuilder andPlaceCountry(string|array $value)
 * @method RuleBuilder andNotPlaceCountry(string|array $value)
 * @method RuleBuilder lang(string|array $value)
 * @method RuleBuilder notLang(string|array $value)
 * @method RuleBuilder orLang(string|array $value)
 * @method RuleBuilder orNotLang(string|array $value)
 * @method RuleBuilder andLang(string|array $value)
 * @method RuleBuilder andNotLang(string|array $value)
 */
class _RuleBuilder
{
}
